version: "3.7"
services:
  postgresql:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    image: windanalysis_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data
