-- SCHEMA作成
CREATE SCHEMA IF NOT EXISTS weather;

-- USER
CREATE USER wasa_user WITH PASSWORD 'wasafee';
-- GRANT
GRANT ALL ON SCHEMA weather TO wasa_user;
GRANT ALL ON ALL TABLES IN SCHEMA weather TO wasa_user;