-- SCHEMA作成
CREATE SCHEMA IF NOT EXISTS weather;

-- USER
CREATE USER wasa_user;
-- GRANT
GRANT USAGE, CREATE ON SCHEMA weather TO wasa_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA weather TO wasa_user;